contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    isoverridable: false
    itemVersion: 1.0.2
    packID: ""
    packName: SOC Phishing Investigation
    prevname: ""
    toServerVersion: ""
dirtyInputs: true
id: 'SOC Proofpoint Message Delivered'
inputSections:
- description: Generic group for inputs
  inputs:
  - Shadow
  name: General (Inputs group)
inputs:
- description: In Shadow Mode the Playbook will run in a testing only mode where it
    prints to the war room but will not take disruptive actions
  key: Shadow
  playbookInputQuery: null
  required: true
  value:
    simple: "false"
name: SOC Proofpoint Message Delivered
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: fcd8a90f-5f53-4dc4-8ade-48374a66b4ec
starttaskid: "0"
tags:
- SOC
- PoV
- Phishing
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0b9d53d3-d66f-4715-8249-de216ec9808d
      iscommand: false
      name: ""
      version: -1
    taskid: 0b9d53d3-d66f-4715-8249-de216ec9808d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 676.25,
          "y": 50
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: errorPath
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "27"
      '#none#':
      - "12"
    note: true
    quietmode: 2
    scriptarguments:
      ignore-outputs:
        simple: "false"
      includeCampaignForensics:
        simple: "true"
      threatId:
        simple: ${alert.proofpointtapthreatid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns forensics evidence.
      id: 72dec84b-74bf-42d6-ac3f-45d424fa71b1
      iscommand: true
      name: Get Forensic Information
      script: '|||proofpoint-get-forensics'
      type: regular
      version: -1
    taskid: 72dec84b-74bf-42d6-ac3f-45d424fa71b1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 676.25,
          "y": 540
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: errorPath
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "27"
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      forensicdnsmarkdown:
        complex:
          accessor: DNS
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicfilemarkdown:
        complex:
          accessor: File
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicnetworkmarkdown:
        complex:
          accessor: Network
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicsummarymarkdown:
        complex:
          accessor: Behavior
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: f84ce61f-e6c8-4513-8642-13337099b65c
      iscommand: true
      name: Summarize Forensic Info
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: f84ce61f-e6c8-4513-8642-13337099b65c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1743,
          "y": 880
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Proofpoint.Report.Behavior
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9e104c65-87b3-4525-849d-2a7e577af0c2
      iscommand: false
      name: Forensic Info Exists?
      type: condition
      version: -1
    taskid: 9e104c65-87b3-4525-849d-2a7e577af0c2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1402.5,
          "y": 710
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: errorPath
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "27"
      '#none#':
      - "15"
      - "20"
    note: false
    quietmode: 2
    reputationcalc: 2
    scriptarguments:
      text:
        simple: ${alert.proofpointtapthreatinfomap.threat}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: 1c248b3a-febd-494c-ba71-1445f5db9f18
      iscommand: true
      name: Create Indicator from Threat
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 1c248b3a-febd-494c-ba71-1445f5db9f18
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1066.75,
          "y": 1210
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b9b18ac2-1779-4228-8ca6-a1ee4314025e
      iscommand: false
      name: TIM - Enrichment
      type: title
      version: -1
    taskid: b9b18ac2-1779-4228-8ca6-a1ee4314025e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1066.75,
          "y": 1050
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: errorPath
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "27"
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        simple: ${alert.proofpointtapthreatinfomap}
      indicatorType:
        complex:
          accessor: threatType
          root: alert.proofpointtapthreatinfomap
          transformers:
          - args:
              limit: {}
              replaceWith:
                value:
                  simple: file
              toReplace:
                value:
                  simple: attachment
            operator: replace
          - args:
              limit: {}
              replaceWith:
                value:
                  simple: url
              toReplace:
                value:
                  simple: url
            operator: replace
      reliability:
        simple: C - Fairly reliable
      score:
        simple: "2"
      vendor:
        simple: Proofpoint
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Add DBot score to context for indicators with custom vendor, score,
        reliability, and type.
      id: 9fb7e578-9268-43a6-b3bc-cc0d65ea2390
      iscommand: false
      name: Assign Proofpoint DBot Score
      script: AddDBotScoreToContext
      type: regular
      version: -1
    taskid: 9fb7e578-9268-43a6-b3bc-cc0d65ea2390
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 1380
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: errorPath
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "27"
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${alert.proofpointtapthreatinfomap.threat}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the overall score for the indicator as calculated by DBot.
      id: 421aad89-5905-4716-abe1-d1f2791c7f81
      iscommand: false
      name: Get Indicator Scores
      script: GetIndicatorDBotScoreFromCache
      type: regular
      version: -1
    taskid: 421aad89-5905-4716-abe1-d1f2791c7f81
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 426.25,
          "y": 1550
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScoreCache.Score
          operator: greaterThan
          right:
            value:
              simple: "2"
        - left:
            iscontext: true
            value:
              simple: Proofpoint.Report.Behavior.Malicious
          operator: isTrue
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: af9b8366-3cce-474d-89a6-2704c49d90c8
      iscommand: false
      name: Remediation Required?
      type: condition
      version: -1
    taskid: af9b8366-3cce-474d-89a6-2704c49d90c8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 576.25,
          "y": 1880
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: errorPath
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "27"
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 9b0af67b-973c-47f0-9a0a-df864e3eba64
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 9b0af67b-973c-47f0-9a0a-df864e3eba64
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 576.25,
          "y": 2380
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 89886dee-4e3e-4c9f-8414-ad151cc66e54
      iscommand: false
      name: Analysis
      type: title
      version: -1
    taskid: 89886dee-4e3e-4c9f-8414-ad151cc66e54
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 576.25,
          "y": 1720
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: errorPath
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "27"
      '#none#':
      - "21"
    note: true
    quietmode: 0
    scriptarguments:
      url:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: alert.proofpointtapthreatinfomap.threatType
              operator: isEqualString
              right:
                value:
                  simple: url
          root: alert.proofpointtapthreatinfomap
          transformers:
          - args:
              field:
                value:
                  simple: threat
            operator: getField
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Converts the contents of a URL to an image file or a PDF file.
      id: e0b5df0d-7ce6-448b-9b78-20fce7de7513
      iscommand: true
      name: Rasterize URL
      script: '|||rasterize'
      type: regular
      version: -1
    taskid: e0b5df0d-7ce6-448b-9b78-20fce7de7513
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1157.25,
          "y": 1380
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: errorPath
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "27"
      '#none#':
      - "19"
    note: true
    quietmode: 0
    scriptarguments:
      method:
        simple: GET
      url:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: alert.proofpointtapthreatinfomap.threatType
              operator: isEqualString
              right:
                value:
                  simple: url
          root: alert.proofpointtapthreatinfomap
          transformers:
          - args:
              field:
                value:
                  simple: threat
            operator: getField
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends http request. Returns the response as json.
      id: e4b5ffa1-0a65-42f4-9a30-8404e27ff685
      iscommand: false
      name: Request raw HTML
      script: http
      type: regular
      version: -1
    taskid: e4b5ffa1-0a65-42f4-9a30-8404e27ff685
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1302.5,
          "y": 1550
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6284baff-3fb9-461a-889d-645f171e605c
      iscommand: false
      name: Forensics
      type: title
      version: -1
    taskid: 6284baff-3fb9-461a-889d-645f171e605c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 676.25,
          "y": 380
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4e618c0d-6718-4b0f-85f9-d7084050e938
      iscommand: false
      name: Remediation
      type: title
      version: -1
    taskid: 4e618c0d-6718-4b0f-85f9-d7084050e938
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 721.5,
          "y": 2050
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3f82b702-96b0-463f-8a6f-c858b4ebb229
      iscommand: false
      name: Manual Review
      type: regular
      version: -1
    taskid: 3f82b702-96b0-463f-8a6f-c858b4ebb229
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 721.5,
          "y": 2210
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: d681ec2a-c458-4580-8db4-aba1209b3b18
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: d681ec2a-c458-4580-8db4-aba1209b3b18
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2550
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3d1e4f0a-e201-4cc3-a624-3932fef5c345
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 3d1e4f0a-e201-4cc3-a624-3932fef5c345
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 2720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2730,
        "width": 2073,
        "x": 50,
        "y": 50
      }
    }
  }
