adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    isoverridable: false
    itemVersion: 1.0.5
    packID: ""
    packName: SOC Phishing Investigation
    prevname: ""
    supportedModules: []
    toServerVersion: ""
dirtyInputs: true
id: SOC Phishing Investigation
inputs: []
name: SOC Phishing Investigation
outputs: []
quiet: true
sourceplaybookid: SOC Phishing Investigation
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4a533215-5bf9-4d73-8cb7-27d01a778163
      iscommand: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 4a533215-5bf9-4d73-8cb7-27d01a778163
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: StringContainsArray
          right:
            value:
              simple: Proofpoint TAP v2
      label: ProofPoint TAP
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      ProofPoint TAP:
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0132495c-9ff3-4285-8e94-b322ca0ad372
      iscommand: false
      name: Which Brand Should be used?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 0132495c-9ff3-4285-8e94-b322ca0ad372
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 82e30d51-0e81-418e-8300-de3015d8ba74
      iscommand: false
      name: ProofPoint TAP
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 82e30d51-0e81-418e-8300-de3015d8ba74
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 172.5,
          "y": 380
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: type
                root: alert
                transformers:
                - operator: toLowerCase
          operator: containsString
          right:
            value:
              simple: message delivered
      label: Message Delivered
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: type
                root: alert
                transformers:
                - operator: toLowerCase
          operator: containsString
          right:
            value:
              simple: click permitted
      label: Click Permitted
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      Click Permitted:
      - "8"
      Message Delivered:
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 76b09b3a-0e92-4370-8c77-ef6499dbcb07
      iscommand: false
      name: Alert Type
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 76b09b3a-0e92-4370-8c77-ef6499dbcb07
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 172.5,
          "y": 540
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 40d75ba9-c56b-4654-824d-93aa56e66731
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 40d75ba9-c56b-4654-824d-93aa56e66731
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 880
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      ShadowMode:
        simple: ${shadow_mode}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 372b1fed-48a1-48fa-8131-cb1c427f123b
      iscommand: false
      name: SOC Proofpoint Click Permitted
      playbookId: SOC Proofpoint Click Permitted
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: 372b1fed-48a1-48fa-8131-cb1c427f123b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 172.5,
          "y": 710
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      ShadowMode:
        simple: ${shadow_mode}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: d2e4b815-6686-4711-8504-bcec9c4a364b
      iscommand: false
      name: SOC Proofpoint Message Delivered
      playbookId: SOC Proofpoint Message Delivered
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: d2e4b815-6686-4711-8504-bcec9c4a364b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 710
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_5_#default#": 0.9
    },
    "paper": {
      "dimensions": {
        "height": 890,
        "width": 932.5,
        "x": 50,
        "y": 50
      }
    }
  }
