adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    isoverridable: false
    itemVersion: 1.0.5
    packID: ""
    packName: SOC Phishing Investigation
    prevname: ""
    supportedModules: []
    toServerVersion: ""
dirtyInputs: true
id: SOC Proofpoint Click Permitted
inputSections:
- description: Generic group for inputs
  inputs:
  - ShadowMode
  name: General (Inputs group)
inputs:
- description: Shadow Mode is a key safety mechanism. It ensures actions like isolate_endpoint
    or disable_user are logged but not executed in test scenarios.
  key: ShadowMode
  playbookInputQuery: null
  required: false
  value:
    simple: "true"
name: SOC Proofpoint Click Permitted
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: fcd8a90f-5f53-4dc4-8ade-48374a66b4ec
starttaskid: "0"
tags:
- SOC
- PoV
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 247f2e71-72a8-4dd2-86a2-638b63d9f62b
      iscommand: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 247f2e71-72a8-4dd2-86a2-638b63d9f62b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: errorPath
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "12"
    note: true
    quietmode: 2
    scriptarguments:
      ignore-outputs:
        simple: "false"
      includeCampaignForensics:
        simple: "true"
      threatId:
        simple: ${alert.proofpointtapthreatid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns forensics evidence.
      id: 4706582a-b3ae-4ddb-85d6-528de14fd8bb
      iscommand: true
      name: Get Forensic Information
      playbooktaskmissingcomponent: null
      script: '|||proofpoint-get-forensics'
      type: regular
      version: -1
    taskid: 4706582a-b3ae-4ddb-85d6-528de14fd8bb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 540
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: errorPath
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      forensicsummarymarkdown:
        complex:
          accessor: Report
          root: Proofpoint
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 6f1d9309-a341-492f-87b0-b4705ef3955a
      iscommand: true
      name: Summarize Forensic Info
      playbooktaskmissingcomponent: null
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: 6f1d9309-a341-492f-87b0-b4705ef3955a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 880
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Proofpoint.Report
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6c5b1e51-bd47-449d-87c2-b173c8288ddb
      iscommand: false
      name: Forensic Info Exists?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 6c5b1e51-bd47-449d-87c2-b173c8288ddb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 710
        }
      }
  "13":
    continueonerror: true
    continueonerrortype: errorPath
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "20"
      - "15"
    note: false
    quietmode: 2
    reputationcalc: 2
    scriptarguments:
      text:
        simple: |-
          ${alert.proofpointtapsuspiciousurl}
          ${alert.proofpointtapclickip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: 087af4d7-24b4-482f-837a-870677eb53d7
      iscommand: true
      name: Create Indicator from Threat
      playbooktaskmissingcomponent: null
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 087af4d7-24b4-482f-837a-870677eb53d7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 545.25,
          "y": 1210
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 297fa85e-92c7-4cfe-84b8-9a54dfca2746
      iscommand: false
      name: TIM - Enrichment
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 297fa85e-92c7-4cfe-84b8-9a54dfca2746
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 545.25,
          "y": 1050
        }
      }
  "15":
    continueonerror: true
    continueonerrortype: errorPath
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        simple: ${alert.proofpointtapsuspiciousurl}
      indicatorType:
        simple: url
      reliability:
        simple: C - Fairly reliable
      score:
        simple: "2"
      vendor:
        simple: Proofpoint
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Add DBot score to context for indicators with custom vendor, score,
        reliability, and type.
      id: f6d59bd2-bcc7-43b0-88f6-03581a7edf3c
      iscommand: false
      name: Assign Proofpoint DBot Score
      playbooktaskmissingcomponent: null
      script: AddDBotScoreToContext
      type: regular
      version: -1
    taskid: f6d59bd2-bcc7-43b0-88f6-03581a7edf3c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1316.75,
          "y": 1550
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: errorPath
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${alert.proofpointtapsuspiciousurl}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the overall score for the indicator as calculated by DBot.
      id: 15e8dfe3-48d6-4cf2-81c2-0d00d4ad5333
      iscommand: false
      name: Get Indicator Scores
      playbooktaskmissingcomponent: null
      script: GetIndicatorDBotScoreFromCache
      type: regular
      version: -1
    taskid: 15e8dfe3-48d6-4cf2-81c2-0d00d4ad5333
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1316.75,
          "y": 1720
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScoreCache.Score
          operator: greaterThan
          right:
            value:
              simple: "2"
        - left:
            iscontext: true
            value:
              simple: Proofpoint.Report.Behavior.Malicious
          operator: isTrue
        - left:
            iscontext: true
            value:
              simple: Core.value
          operator: isFalse
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6f713944-9fb2-4e8b-8071-cdc73f3cfcd6
      iscommand: false
      name: Remediation Required?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 6f713944-9fb2-4e8b-8071-cdc73f3cfcd6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1607.25,
          "y": 2220
        }
      }
  "18":
    continueonerror: true
    continueonerrortype: errorPath
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: c44952d7-58d2-4ffe-8503-0b128945577c
      iscommand: true
      name: Close
      playbooktaskmissingcomponent: null
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: c44952d7-58d2-4ffe-8503-0b128945577c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1607.25,
          "y": 2720
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ccbb13e0-d852-4431-8b3e-380a815ab99d
      iscommand: false
      name: Analysis
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: ccbb13e0-d852-4431-8b3e-380a815ab99d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1462,
          "y": 1890
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: errorPath
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "21"
    note: true
    quietmode: 0
    scriptarguments:
      url:
        simple: ${alert.proofpointtapsuspiciousurl}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Converts the contents of a URL to an image file or a PDF file.
      id: d5e99b0a-ac5c-4a4d-8715-b9394b4cb9bb
      iscommand: true
      name: Rasterize URL
      playbooktaskmissingcomponent: null
      script: '|||rasterize'
      type: regular
      version: -1
    taskid: d5e99b0a-ac5c-4a4d-8715-b9394b4cb9bb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 640.5,
          "y": 1380
        }
      }
  "21":
    continueonerror: true
    continueonerrortype: errorPath
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "26"
    note: true
    quietmode: 0
    scriptarguments:
      method:
        simple: GET
      url:
        simple: ${alert.proofpointtapsuspiciousurl}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends http request. Returns the response as json.
      id: 8ac2e16c-33f7-45cd-8ecd-d60aece39da8
      iscommand: false
      name: Request raw HTML
      playbooktaskmissingcomponent: null
      script: http
      type: regular
      version: -1
    taskid: 8ac2e16c-33f7-45cd-8ecd-d60aece39da8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690.5,
          "y": 1550
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b60e8bb8-ae97-4034-898c-94a40e6419ba
      iscommand: false
      name: Forensics
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: b60e8bb8-ae97-4034-898c-94a40e6419ba
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 380
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ca3e7033-b753-45a2-8bfd-34a25ccfc674
      iscommand: false
      name: Remediation
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: ca3e7033-b753-45a2-8bfd-34a25ccfc674
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1752.5,
          "y": 2390
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: errorPath
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: Core=.
      ip_address:
        simple: ${alert.proofpointtapclickip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the prevalence of an ip, identified by ip_address.
      id: 6ab28560-bb6a-4786-8fe5-958e0325d089
      iscommand: true
      name: Prevalence of Click IP
      playbooktaskmissingcomponent: null
      script: '|||core-get-IP-analytics-prevalence'
      type: regular
      version: -1
    taskid: 6ab28560-bb6a-4786-8fe5-958e0325d089
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1462,
          "y": 2050
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: errorPath
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "30"
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      forensicdnsmarkdown:
        complex:
          accessor: DNS
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicfilemarkdown:
        complex:
          accessor: File
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicnetworkmarkdown:
        complex:
          accessor: Network
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      forensicsummarymarkdown:
        complex:
          accessor: Behavior
          root: Proofpoint.Report
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      httpcookiesmd:
        complex:
          accessor: Cookies
          root: HttpRequest.Response
          transformers:
          - args:
              headers: {}
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
      httprawhtml:
        simple: ${HttpRequest.Response.Body}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 892e8779-f3bf-47fc-88c1-0f0393bc2a47
      iscommand: true
      name: Set Response Data
      playbooktaskmissingcomponent: null
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: 892e8779-f3bf-47fc-88c1-0f0393bc2a47
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 835.75,
          "y": 1720
        }
      }
  "27":
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bebf4945-d6ce-4b9d-8d76-668b92945750
      iscommand: false
      name: Manual Review
      playbooktaskmissingcomponent: null
      type: regular
      version: -1
    taskid: bebf4945-d6ce-4b9d-8d76-668b92945750
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1752.5,
          "y": 2550
        }
      }
  "29":
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f9b453cd-67ef-4050-81db-5ca826bf1404
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: f9b453cd-67ef-4050-81db-5ca826bf1404
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1026.25,
          "y": 3060
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "29"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: d38e6a2d-7e00-445d-851f-fb893be95d10
      iscommand: false
      name: Foundation - Error Handling
      playbookName: Foundation - Error Handling
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: d38e6a2d-7e00-445d-851f-fb893be95d10
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 550,
          "y": 2890
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3070,
        "width": 2082.5,
        "x": 50,
        "y": 50
      }
    }
  }
